language: ruby
rvm:
  - 2.7.0

before_script:
  - chmod +x ./scripts/cibuild.sh

script: "./scripts/cibuild.sh"

# branch whitelist, only for GitHub Pages
branches:
  only:
  - source     # test the source branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: W0GGA2WC6bWSffpOexjjtVGagvm5R3VmbmmI4i/dXNwTfKY8Xij2SGu+LczBXR4pgCGna+wt26/cZbaAWEIy1VKKS7vWCK6+8wmCMJnTPmLoG+7EH5+71tORgCD8FDu6HNnIEJH6UVqbR6807t+AutLIWoPiIf0SJ/75bszb4sfZnoAUtPc5I5tV3CJ0GLUaM2FhqrTJ27Av2zXiaIlq24TwVfmE9J9krGbht/LE1iY8q9+4zym6rMtWTYSh0F4jIBb77GMifjU1fyNlZqr19i3DfMaDRaw9Kg+9DVjm6Z3UgEBNZQ6muMoJgBWwhlx5gEn307xxT7eJyW3daXs9G/To8qddmLMwbOoVxogh7DG1hGAMD9iri2bsEH5IrV1+O/89r4SW3cqasMhFsp6DZlljcJl5Qb/qu2nAOqiWM62pyl3CFOrrzHtIqDZYVuT8mV3IFJw7lAE5rOnkid5l431L9Mks3JquACMVvvPADu5Kj7IZLY6liuMIUmrZD0FC6i+rHNYhJl8K1lx1bXYc3dycZcsrcSb4+/1CXa0ewo+rTl8P4AN+aYzIKm0HGnGgpp4YsTZA0aohNLjLD5qo6qVS8oIZA7GTuhUVuIgzJHexl0FBA/HmdJlsrybfPEbuAR3wiX1924/rIbm8QWAsC108Zd2r+xZyeb6f0H8eXaI=

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # speed up build by caching bundler gem packages

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/cideploy.sh
  on:
    branch: source

# Enable email notifications
notifications:
  email: true

