language: ruby
rvm:
  - 2.7.0

before_script:
 - chmod +x ./scripts/cibuild.sh

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - source     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # html-proofer installation speedup

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # speed up build by caching bundler gem packages

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/cideploy.sh
  on:
    branch: source

# Enable email notifications
notifications:
  email: true

