# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

include: [.nojekyll]

# Site settings
title: Software Pieces
email: fperezsorrosal @ gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains bits and b[iy]tes of software I've compiled
  in the last few years. Hope this can be useful for other passionate
  software engineers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://francisco-perez-sorrosal.github.io" # the base hostname & protocol for your site
twitter_username: fperezsorrosal
github_username:  francisco-perez-sorrosal

# Build settings
markdown: kramdown

# Change default server port
port: 8888

# Plugins (Must be compatible with github)
gems:
  - jekyll-sitemap